module.exports = {
  defaultSidebar: [
    'indroduction',
    {
      type: 'category',
      label: 'Analysis of Algorithms',
      collapsed: false,
      items: [
        'analysis-of-algorithms/asymptotic-analysis',
        'analysis-of-algorithms/worst-average-and-best-cases',
        'analysis-of-algorithms/asymptotic-notations',
        'analysis-of-algorithms/little-O-and-little-omega-notations',
        'analysis-of-algorithms/lower-and-upper-bound-theory',
        'analysis-of-algorithms/analysis-of-loops',
        'analysis-of-algorithms/solving-recurrences',
        'analysis-of-algorithms/amortized-analysis',
        'analysis-of-algorithms/space-complexity',
        'analysis-of-algorithms/pseudo-polynomial-algorithms',
        'analysis-of-algorithms/np-completeness-introduction',
        'analysis-of-algorithms/polynomial-time-approximation-scheme',
        'analysis-of-algorithms/a-time-complexity-question',
        'analysis-of-algorithms/time-complexity-of-building-a-heap',
        'analysis-of-algorithms/time-complexity-of-loop-with-powers',
        'analysis-of-algorithms/big-O-notation',
      ],
    },
    {
      type: 'category',
      label: 'Sorting Algorithms',
      items: [
        'sorting-algorithms/sorting',
        'sorting-algorithms/bubble-sort',
        'sorting-algorithms/selection-sort',
        'sorting-algorithms/insertion-sort',
        'sorting-algorithms/merge-sort',
        'sorting-algorithms/quick-sort',
        'sorting-algorithms/counting-sort',
        'sorting-algorithms/radix-sort',
        'sorting-algorithms/bucket-sort',
        'sorting-algorithms/heap-sort',
        'sorting-algorithms/shell-sort',
      ],
    },
    {
      type: 'category',
      label: 'Searching Algorithms',
      items: [
        'searching-algorithms/linear-search',
        'searching-algorithms/binary-search',
        'searching-algorithms/binary-search-tree',
      ],
    },
    {
      type: 'category',
      label: 'Greedy Algorithms',
      items: [
        'greedy-algorithms/greedy-algorithm',
        'greedy-algorithms/ford-Fulkerson-algorithm',
        'greedy-algorithms/dijkstras-algorithm',
        'greedy-algorithms/kruskals-algorithm',
        'greedy-algorithms/prims-algorithm',
        'greedy-algorithms/huffman-code',
      ],
    },
    {
      type: 'category',
      label: 'Dynamic Programming',
      items: [
        'dynamic-programming/dynamic-programming',
        'dynamic-programming/floyd-warshall-algorithm',
        'dynamic-programming/fongest-common-subsequence',
      ],
    },
  ],
};
